### ISSUE TITLE
Re-enable LTSS-supported versions of SLE 12 products

### ISSUE THREAD

**Issue by sknorr** [doc-suse-com/issue-tracker#28]
There are a few product versions that are set to the state "unsupported" even though they are actually still supported. These are SLES/SLES-SAP/SLE-HA 12 SP1/12 SP2/12 SP3.

The version listings for SLED and SLE-RT are correct, as they do not have LTSS.

12 SP1 goes out of LTSS in May, so it makes little sense to re-enable it and I am going to leave it off the list.

mandatory:

- [x] fix IDs in doc-sle
  - [x] maint/12SP2
  - [x] trans/12SP2
  - [x] maint/12SP3
  - [x] trans/12SP3
- [x] fix IDs in doc-sleha
  - [x] maint/12SP2
  - [x] trans/12SP2
  - [x] maint/12SP3
  - [x] trans/12SP3
- [x] fix IDs in doc-slesforsap
  - [x] maint/12SP2
  - [x] maint/12SP3
- [x] fix DCs in doc-sle
  - [x] trans/12SP2
  - [x] trans/12SP3
- [x] fix DCs in doc-sleha
  - [x] trans/12SP2
  - [x] trans/12SP3

---

additional:

- [ ] fix sc/d links in doc-sle
  - [ ] maint/12SP2
  - [ ] trans/12SP2
  - [ ] maint/12SP3
  - [ ] trans/12SP3
- [ ] fix sc/d links in doc-sleha
  - [ ] maint/12SP2
  - [ ] trans/12SP2
  - [ ] maint/12SP3
  - [ ] trans/12SP3
- [x] fix sc/d links in doc-slesforsap
  - [x] maint/12SP2
  - [x] maint/12SP3

**Comment by ghost** [comment]
We have not yet fixed any URLs in those documents but they are up again.
