### ISSUE TITLE
Change configuration of SLE-WE 12 SP5 to be less SLEDdy

### ISSUE THREAD

**Issue by sknorr** [doc-suse-com/issue-tracker#29]
Our current documentation at doc.suse.com/sled/12-SP5 (for SLE-WE 12 SP5) is pretty confusing, because the documentation itself is still branded SLED 12 SP5. It would be nice to change that without investing a lot of work.

Suggestions:

* Unpublish Deployment Guide and Installation Quick Start, because they don't really match the product.
* In other guides, change the product name at the top of the page (but nowhere else),
* Add a para to book abstracts explaining the SLED/SLE-WE equivalency, i.e. "These are the same packages but installation and support options are different." (If we really want to do this, we could even add this para to all chapter abstracts.)

@taroth21 What do you think?

**Comment by ghost** [comment]
@taroth21 @fsundermeyer 

I looked a bit through the currently published SLED 12 SP5
documentation to check whether I could just comment out the
Deployment and Install Quick Guides and get somewhat useful
documentation for SLE-WE 12 SP5.

What I was producing was not particularly useful.

The remaining guides, even the GNOME User Guide,
contain very few actual changes compared to the SLES guides.

I noticed also that the SLES documentation has almost no
content removed compared to the SLED documentation.

So, what I would suggest to do is the following:

1. Publish a few extra sections that were so far profiled
   as SLED content in the SLES 12 SP5 documentation as well,
   with a remark, that this may only be supported in the
   Workstation Extension. Those are roughly (but that is a fairly complete list):
   * NetworkManager
   * Co-existence of Windows and Linux on the same HDD
   * Automatic Desktop login
   * YaST scanner setup
   * Signing Documents in LibreOffice

2. Completely unpublish the SLED 12 SP5 documentation and
   adding a redirect sled/12-SP5 -> sles/12-SP5 

What do you say?

The following is a list of lines that are currently part of the *SLED 12 SP5* documentation only:
[sles-deletion.txt](https://github.com/doc-suse-com/issue-tracker/files/4294616/sles-deletion.txt).
At 1000 lines, this is not exactly a lot.

**Comment by taroth21** [comment]
@sknorr : Thanks for analyzing the situation! Sounds like a fairly useful compromise to me. But this should only be done in the SLE 12 SP5 maintenance branch. Is this something Dima could work on?

**Comment by ghost** [comment]
Thank you, Tanja!

I am on the way toward pushing the new SLES stuff up and taking SLED stuff down, so I'll just close this issue.

Notably, I enabled the extra content in the English version of the guides only. The other versions are as they were.
