### ISSUE TITLE
Main documentation page is misleading

### ISSUE THREAD

**Issue by paususe** [doc-suse-com/issue-tracker#42]
This is what I see when I access the main documentation page (documentation.suse.com) with Firefox for the first time on my 15.6 FHD laptop:

![documentation-suse-com-design-current1](https://user-images.githubusercontent.com/50680111/91233392-64df7000-e731-11ea-8a6d-a77f3ceacf1f.png)

All the screen real estate is consumed by:
1. Cookie warnin
2. Some introductory text presenting this site
3. A request to answer the docs survey
4. Advice on where to find the release notes and documentation for unsupported products
5. Finally, at the (apparently) bottom of the page, I see a search box

If I were visiting this page for the first time, I would probably use the search box, and then complain I cannot find a link to all the docs for some product. But actually, such link is there! But with so much stuff at the top of the page, I need to scroll down. How many users will scroll down? I'm sure at least some of them will not.

![documentation-suse-com-design-current2](https://user-images.githubusercontent.com/50680111/91233397-65780680-e731-11ea-9467-2b4ff7ec8b55.png)

Here is a suggestion:
1. Make the search bar a bit shorter in height
2. Move the advice about release notes and unsupported products to the end

![documentation-suse-com-design-suggestion](https://user-images.githubusercontent.com/50680111/91233788-3910ba00-e732-11ea-8b0e-ab84d6601099.png)

And here's a second suggestion, adding on top of the previous one: get rid of the "select product" and "select version" headers by including that information in the "view documentation for a product [and version]" header:

![documentation-suse-com-design-suggestion2](https://user-images.githubusercontent.com/50680111/91234093-de2b9280-e732-11ea-9875-d2c1fb005de5.png)

**Comment by ghost** [comment]
Sorry for the late feedback. I changed most of the things you criticized, however. Changes should be out later today.
Going through the list:

> 1. Cookie warning

The last redesign has already removed the old cookie notice (and replaced it with One Trust which does not reappear quite as often, unless you delete cookies). That was probably the biggest offender.


> 2. Some introductory text presenting this site

I think we need at least a bit of this up top, unfortunately.


> 3. A request to answer the docs survey

The survey is currently down and we will link to it differently when we start up again.


> Advice on where to find the release notes and documentation for unsupported products

We *had* the "unsupported products" link at the bottom before and got feedback that it is too well hidden (there are specific people within the company and also outside that really dig old stuff).
However, this will be reorganized in the near future too and should take less space/be more contextualized.

>  Finally, at the (apparently) bottom of the page, I see a search box

Right. 

---

As to the suggestions:

>  Make the search bar a bit shorter in height

I have removed the title and reduced spacing around the search a little


> Move the advice about release notes and unsupported products to the end

I have not done that, given prior feedback about old documentation being relevant to a certain class of people.

> get rid of the "select product" and "select version" headers by including that information in the "view documentation for a product [and version]" header:

Done.
