### ISSUE TITLE
SUSE Manager 4.1 Documentation - Users

### ISSUE THREAD

**Issue by jorx-dev** [doc-suse-com/issue-tracker#43]
Hello,
In the Administration Guide of SUSE Manager's Users section there is an statement that I think is incomplete. At the beginning just after the 1st paragraph, it reads:

NOTE: The Users menu is only available if you are logged in with a SUSE Manager administrator account.

I think I should be:

NOTE: The Users menu is only available if you are logged in with a SUSE Manager administrator account or an Organization administrator account.

regards,

**Comment by ghost** [comment]
Thank you for your feedback! I opened an issue in the appropriate SUMA/Uyuni doc repo. Since you should be able to see the linked issue, I will close here.
