### ISSUE TITLE
openscap scans in Salt Clients

### ISSUE THREAD

**Issue by jorx-dev** [doc-suse-com/issue-tracker#44]
Hello,

On https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/administration/openscap.html there is a note at the beginning that claims oscap scans only work for traditional clients.

NOTE: OpenSCAP auditing is available for use with traditional clients only. It is not available on Salt clients.

In my case, I've been able to launch oscap scans on a SLES 15 SP1 Salt Client from the SUSE Manager WebUI. So what's wrong ?

thanks,

**Comment by ghost** [comment]
Thank you for your feedback! I've reported it in the Uyuni/SUSE Manager upstream documentation repo and will be closing here, please follow there.
