### ISSUE TITLE
Bad URL at SUMA - Salt manual - YOMI section

### ISSUE THREAD

**Issue by jorx-dev** [doc-suse-com/issue-tracker#45]
Hello,
Please check bad URL at 
https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/salt/formula-yomi.html
Procedure: Configuring the Yomi Software Formula
at step 5
found:
https://scc/suse.com
should be:
https://scc.suse.com

cheers,

**Comment by ghost** [comment]
Thank you & sorry for the wait! This has been fixed in the sources of the SUSE Manager docs and will be included in the next documentation update for the product.
