### ISSUE TITLE
Version selection not possible when using Internet Explorer

### ISSUE THREAD

**Issue by spurgeonr** [doc-suse-com/issue-tracker#5]
I have now tried this on 2 different systems, and have the same result:  

After selecting the Product, no Versions appear for selection.

Happy to provide further info, if needed.

**Comment by fsundermeyer** [comment]
function populateVersionSelect(Productid) {   
      ...
      instruction[0].remove;
      ...
    }

Error: The object does not support the property or method "remove"
IE 11.09 on Win 7

**Comment by ghost** [comment]
This has finally been fixed -- it was indeed a one-liner in the end.
