### ISSUE TITLE
Shorten Open Graph title/desc & meta desc

### ISSUE THREAD

**Issue by ghost** [doc-suse-com/issue-tracker#52]
Our og: tags should use shorter titles (60 char max) and descriptions (65 char max), apparently. These will need to be cut down via the stylesheets.

Similarly, our meta descs should apparently be cut down to 75~150 chars.

**Comment by janajaeger** [comment]
Cut down the og:description even more to a max of 55 chars to meet the twitter:description requirements.

**Comment by janajaeger** [comment]
Going forward with Smart Docs and new meta data, this will be handled differently. Also, the limits are not quite correct anymore. Moving this issue over to Jira and closing this one.
Legacy docs will still have the chopping mechanism in place, but Smart Docs authors have social-descr and meta title tags to achieve this.
