### ISSUE TITLE
[Wrong Sample][Container Guide]

### ISSUE THREAD

**Issue by EwertonJordao** [doc-suse-com/issue-tracker#55]
https://documentation.suse.com/sle-containers/all/html/SLE-container-guide/cha-bci.html#status-lifecycle-bci

Now:
```console
skopeo inspect docker://registry.suse.com/bci/bci-micro:15.4 | jq '.Labels["com.suse.techpreview"]'
skopeo inspect docker://registry.suse.com/bci/bci-base:15.4 | jq '.Labels["com.suse.techpreview"]'
null
```
Expected:
```console
skopeo inspect docker://registry.suse.com/bci/bci-micro:15.4 | jq '.Labels["com.suse.supportlevel"]'
"techpreview"
skopeo inspect docker://registry.suse.com/bci/bci-base:15.4 | jq '.Labels["com.suse.supportlevel"]'
"l3"
```

**Comment by tomschr** [comment]
Thanks @EwertonJordao, I redirected it to the person in charge.

**Comment by tomschr** [comment]
It was already added to our daily update here: https://susedoc.github.io/doc-sle/main/single-html/SLES-container/#status-lifecycle-bci
For the official documentation you have to wait til Friday. :slightly_smiling_face:

**Comment by EwertonJordao** [comment]
@tomschr I saw recently the documentation and still the wrong sample. Any problem with that sugestion ?

**Comment by tomschr** [comment]
> @tomschr I saw recently the documentation and still the wrong sample. Any problem with that sugestion ?

We moved the Container Guide to a new location. This is work in progress. Once this is done, the URL will be redirected to the new location.
