### ISSUE TITLE
SLES and SLES for SAP 15 SP4 Release Notes refer to Kernel 5.3 and not 5.14

### ISSUE THREAD

**Issue by wombelix** [doc-suse-com/issue-tracker#56]
Hi,

apologies if that's the wrong repo to report the issue, but nothing is mentioned on the release notes page so I assumed that it's part of SUSE docs.

Kernel version 5.14 is shipped by default with SLES and SLES for SAP 15 SP4 but in the vanilla SLES release notes, it's not clearly stated and 5.3 as well as 5.14 mentioned in two sections. In the SLES for SAP release notes, 5.3 is mentioned in General Changes and 5.14 not at all.

Both release notes should contain a clear statement in the General Changes section that the default Kernel Version changed to 5.14.

# SLES 15 SP4 Release Notes
Kernel 5.3 mentioned in Kernel limits: https://suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html#kernel-limits
Kernel 5.14 mentioned in iotop support: https://suse.com/releasenotes/x86_64/SUSE-SLES/15-SP4/index.html#boo-1200669

# SLES for SAP 15 SP4 Release Notes
Kernel 5.3 mentioned in General Changes: https://www.suse.com/releasenotes/x86_64/SLE-SAP/15-SP4/index.html#id-general-changes
```
Kernel
SLE 15 SP4 will come with Kernel 5.3. This new kernel release includes upstream features like 16 million new IPv4 addresses, utilization clamping support in the task scheduler, power efficient userspace waiting with the umwait x86 instructions and many more.
```
Kernel 5.14 not mentioned at all

**Comment by KucharczykL** [comment]
Hi, thank you for the report! I have created a tracking issue internally, and fixed it in the source.

Reference: https://jira.suse.com/browse/DOCTEAM-908
