### ISSUE TITLE
Wrong directory OLD-zh_CN at d.s.c

### ISSUE THREAD

**Issue by raulillo82** [doc-suse-com/issue-tracker#57]
When releasing the 4.3.9 update for d.s.c Tom noticed that there was a directory called `OLD-zh_CN` , which does not seem to belong there. Could you please have a look into it? Let me know if I can help.
Unrelated, but other than that, the new documentation update seems to be fine.

**Comment by tomschr** [comment]
@raulillo82 Thanks Rául, but if I'm not mistaken, you need to remove it in the internal GitLab instance at: https://gitlab.suse.de/susedoc/docserv-external-tree-suma
This looks like the wrong place. :slightly_smiling_face: 

Maybe open the bug there and assign it to Joseph? He did the last commit.
