### ISSUE TITLE
Neuvector docs not listed on front page of docs 

### ISSUE THREAD

**Issue by pwl0lwp** [doc-suse-com/issue-tracker#58]
The "Core technical documentation for SUSE products" on the front page of docs.suse.com doesn't include Neuvector as a product category.

Instead, customers must navigate to  "Rancher"  and then find it under that category.

This is non-intuitive as "Neuvector" isn't necessarily marketed as "Rancher Neuvector" 

Proposal:  include a direct link from  the "Core technical documentation for SUSE products" set to "Neuvector" --> (currently https://open-docs.neuvector.com/ )

**Comment by tomschr** [comment]
Thank you @pwl0lwp for the report! Much appreciated. :+1: 

It's integrated now here: https://documentation.suse.com/#neuvector
