### ISSUE TITLE
Download Doc as ZIP is confusing 

### ISSUE THREAD

**Issue by taroth21** [doc-suse-com/issue-tracker#7]
While it's a good idea to offer ZIPs with the complete product docs for download, the option is potentially confusing:

- It is not specified that the ZIP only includes the 'core' product documentation, and not the additional docs that are listed (currently uncategorized)  at the bottom such as SUSE Best Practices, Release Notes and other related documents. Maybe this will become clearer as soon as we have added a category like 'Additional Documentation' or such.

- The 'Download Documentation as ZIP' option is especially confusing for the *unsupported* product versions. For those, only the (uncategorized) additional documentations such as release notes and SUSE Best Practices are listed. Customers might be surprised to find that the ZIP contains the product documentation (which is not listed anywhere on the page) and not the documents listed on the page as one could have expected. Perhaps we can add a sentence at the top that for unsupported products the product documentation is only available as ZIP and that other related docs can be accessed via the links below.

**Comment by ghost** [comment]
Changes:

* ZIP buttons have been removed, following a complaint via @rockarong that they look too different from normal documentation links and therefore aren't seen/seen only as confusing.
* There is now an "Archives" category on each page, with a single entry for the ZIP file.
* The "Archives" category is listed first on pages for unsupported products, last for other products.
* It has a category description matching what Tanja suggested.

docserv repo:  SHA a1fde8daf36986e63cafb8ea433e01d0697006d5, SHA 1e953cbb518fe673f313cf23f669357b5058589a
